# File format info: https://moz-l10n-config.readthedocs.io/en/latest/fileformat.html
basepath = "."

locales = [
	'ar',
	'de',
	"en-x-owo",
	"es-419",
	"et",
	"fr",
	"it",
	"ja",
	"ko",
	"nb-NO",
	'nl',
	"pl",
	"pt-BR",
	"ru",
	"vi",
	"zh-Hans",
	"zh-Hant",
]

[[paths]]
    reference = "gui/public/i18n/en/*.ftl"
    l10n = "gui/public/i18n/{locale}/*.ftl"
