# This workflow will build the update manifest for the updater and update a GitHub release

name: Generate update manifest

on:
  workflow_dispatch:
  release:
    types: [released]

jobs:
  generate-manifest:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/setup-node@v6
        with:
          node-version: '22.x'

      - name: Generate update-manifest.json
        run: |
          npx @slimevr/update-manifest-generator@latest

      - uses: actions/upload-artifact@v6
        with:
          name: "update-manifest.json"
          path: ./update-manifest.json

      - name: Upload update-manifest.json to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ secrets.UPDATE_MANIFEST_RELEASE_TAG }}
          files: ./update-manifest.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
